
# OP-Yield: Adaptation of Oliver and Powers (1978) Yield Table

* Date/time: `r Sys.time()`

## Yield Summary


```{r, echo=FALSE}

TABLE_OUT <- yield.summary.table(OP.tab.cal())
yth1 <- switch(ineq.cf(),
               "Oliver & Powers 0_1"= "Oliver and Powers (1978) Total Stem CF Volume, 1-foot stump",
               "Wensel & Olson 0_1" = "Wensel and Olson (1995) Total Stem CF Volume, 1-foot stump",
               "MacLean&Berger 4_1" = "MacLean and Berger (1976) CF Volume, 4-inch top, 1-foot stump")
yth2 <- switch(ineq.bf(),
                 "Wensel & Olson 8_1" = "Wensel and Olson (1995): Scribner BF Volume 8-inch top, 1-foot stump",
                 "Wensel & Olson 6_1" = "Wensel and Olson (1995): Scribner BF Volume 6-inch top, 1-foot stump",
                 "Wensel & Olson 4_1" = "Wensel and Olson (1995): Scribner BF Volume 4-inch top, 1-foot stump",
                 "MacLean&Berger v_1" = "MacLean and Berger (1976) Scribner BF Volume, 4-inch top, 1-foot stump")

```

* CF Volume equation: `r yth1`
* BF Volume equation: `r yth2`


```{r, echo=FALSE,warning=FALSE}
suppressWarnings(suppressMessages(library("pander")))   # suppress warnings

panderOptions('table.continues', '')
pander(TABLE_OUT, split.table = 100, round=1, style = 'rmarkdown')

```

## Annual Volume Increment

```{r plot1, fig.height=4, echo=FALSE}
p1()
```


## Growing Stock Table

* Age: `r GS.Table.Age()`, Year: `r GS.Table.Age()+Plant.yr()`


```{r, echo=FALSE,warning=FALSE}

GT_TABLE_OUT <- Growing.stock.table(OP.tab.cal(), cf.merch.lim = cf.merch.lim(), Age=GS.Table.Age())
suppressWarnings(suppressMessages(library("pander")))   # suppress warnings

panderOptions('table.continues', '')
pander(GT_TABLE_OUT, split.table =100, round=1, style = 'rmarkdown')

```

## Stand Density

```{r plot2, fig.height=4, echo=FALSE}
p3()
```


## Density by Crown Class

```{r plot3, fig.height=4, echo=FALSE}
p2()
```

## Precommercial Thinning Summary

* Year: `r ifelse(pct.age()>0, pct.age()+Plant.yr(), "No PCT")`


```{r, echo=FALSE,warning=FALSE}

PCT_TABLE_OUT <- PCT.summary.table(OP.tab.cal())
suppressWarnings(suppressMessages(library("pander")))   # suppress warnings

panderOptions('table.continues', '')
pander(PCT_TABLE_OUT, split.table = 100, round=1, style = 'rmarkdown')

```

